/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CouncilSelector: typeof import('./src/components/CouncilSelector.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    ProcessStep: typeof import('./src/components/ProcessStep.vue')['default']
    ResourceConsentDetails: typeof import('./src/components/ResourceConsentDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    TaskDialog: typeof import('./src/components/TaskDialog.vue')['default']
    TaskManagement: typeof import('./src/components/TaskManagement.vue')['default']
  }
}
