/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CouncilSelector: typeof import('./src/components/CouncilSelector.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    ProcessStep: typeof import('./src/components/ProcessStep.vue')['default']
    PropertyManager: typeof import('./src/components/registration/PropertyManager.vue')['default']
    ResourceConsentDetails: typeof import('./src/components/ResourceConsentDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    Step10NESHazards: typeof import('./src/components/request-steps/Step10NESHazards.vue')['default']
    Step11AEE: typeof import('./src/components/request-steps/Step11AEE.vue')['default']
    Step12PlanAssessment: typeof import('./src/components/request-steps/Step12PlanAssessment.vue')['default']
    Step13AffectedParties: typeof import('./src/components/request-steps/Step13AffectedParties.vue')['default']
    Step14SpecialistReports: typeof import('./src/components/request-steps/Step14SpecialistReports.vue')['default']
    Step15ProposedConditions: typeof import('./src/components/request-steps/Step15ProposedConditions.vue')['default']
    Step16Declarations: typeof import('./src/components/request-steps/Step16Declarations.vue')['default']
    Step17Review: typeof import('./src/components/request-steps/Step17Review.vue')['default']
    Step1ApplicantProposal: typeof import('./src/components/request-steps/Step1ApplicantProposal.vue')['default']
    Step1CouncilSelection: typeof import('./src/components/request-steps/Step1CouncilSelection.vue')['default']
    Step2NaturalHazards: typeof import('./src/components/request-steps/Step2NaturalHazards.vue')['default']
    Step2RequestType: typeof import('./src/components/request-steps/Step2RequestType.vue')['default']
    Step3NESAssessment: typeof import('./src/components/request-steps/Step3NESAssessment.vue')['default']
    Step3ProcessInfo: typeof import('./src/components/request-steps/Step3ProcessInfo.vue')['default']
    Step4ApplicantDetails: typeof import('./src/components/request-steps/Step4ApplicantDetails.vue')['default']
    Step4Approvals: typeof import('./src/components/request-steps/Step4Approvals.vue')['default']
    Step5Consultation: typeof import('./src/components/request-steps/Step5Consultation.vue')['default']
    Step5PropertyDetails: typeof import('./src/components/request-steps/Step5PropertyDetails.vue')['default']
    Step6ConsentInfo: typeof import('./src/components/request-steps/Step6ConsentInfo.vue')['default']
    Step6DeliveryPayment: typeof import('./src/components/request-steps/Step6DeliveryPayment.vue')['default']
    Step6Documents: typeof import('./src/components/request-steps/Step6Documents.vue')['default']
    Step7AEE: typeof import('./src/components/request-steps/Step7AEE.vue')['default']
    Step7BConsentDetails: typeof import('./src/components/request-steps/Step7BConsentDetails.vue')['default']
    Step7ConsentType: typeof import('./src/components/request-steps/Step7ConsentType.vue')['default']
    Step8ProposalDetails: typeof import('./src/components/request-steps/Step8ProposalDetails.vue')['default']
    Step9SiteEnvironment: typeof import('./src/components/request-steps/Step9SiteEnvironment.vue')['default']
    Step9Submission: typeof import('./src/components/request-steps/Step9Submission.vue')['default']
    TaskDialog: typeof import('./src/components/TaskDialog.vue')['default']
    TaskManagement: typeof import('./src/components/TaskManagement.vue')['default']
  }
}
